#! /bin/bash

# ajubatus v0.1 -- Renames groups of photos according to a scheme.
#
# Renames photo and video files according to the scheme
# YYYY-MM-DD_photographer_camera_NNNN.EXT.  Currently, this script is only
# compatible with renaming files from Nikon DSLRs such the NIkon D600.
#
#
#
# ~~~ License ~~~
#
# Copyright 2020 Paul R. Ramer (prramer)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# You may use this program under the terms of the GNU GPL v3.
# https://www.gnu.org/licenses/gpl-3.0.en.html



# Environment variables
#
# Set these to make ajubatus automatically set the variables it uses for
# renaming photos.  Note that command line arguments override environment
# variables.
#
# $ajubatus_camera          Sets $camera
# $ajubatus_capture_date    Sets $capture_date
# $ajubatus_photographer    Sets $photographer
# $ajubatus_old_scheme      Sets $old_scheme

# Declaring constants
readonly tab_usage="      "  # For printing a custom tab size when displaying usage.
readonly logic_true="1"      # For testing truth.

# Declaring variables
camera=""
capture_date=""
new_scheme=""
old_scheme=""
photographer=""
program_name="ajubatus"
multi_capture_date=""       # Set when in muliple capture date mode.
dirs_list=""                # List of directories to traverse for renaming.

# Defining arrays
dirs_to_traverse=()         # Array of directories to traverse for renaming.

# Error codes
error_normal=0
error_missing_args=1

# Declaring and defining functions
print_usage() {
    echo "usage: $program_name [-d capture_date] [-c camera] [-p photographer] [-s old_name_scheme]"
    echo "$tab_usage $program_name -m [-c camera] [-p photographer] [-s old_name_scheme]"
    echo "$tab_usage $program_name -h"

}
exit_missing_args() {
    echo "$program_name: Missing arguments."
    print_usage
    exit $error_missing_args
}


# Command line options.
while getopts ":hc:d:p:s:m" arg; do
    case $arg in
        h) print_usage; exit $error_normal;; #Print usage help.
        c) camera=$OPTARG;;
        d) capture_date=$OPTARG;;
        p) photographer=$OPTARG;;
        s) old_scheme=$OPTARG;;
        m) multi_capture_date=$logic_true;;
    esac
done


# Don't run if neither multiple capture dates mode is set or a single capture
# date isn't specified.
if [ ! "$multi_capture_date" == "$logic_true" ]; then
    if [ "$capture_date" == "" ]; then
        if [ "$ajubatus_capture_date" == "" ]; then
            exit_missing_args
        else
            capture_date=$ajubatus_capture_date
        fi
    fi
fi

# Don't run if the camera model isn't set.
if [ "$camera" == "" ]; then
    if [ "$ajubatus_camera" == "" ]; then
        exit_missing_args
    else
        camera=$ajubatus_camera
    fi
fi

# Don't run if the photographer isn't set.
if [ "$photographer" == "" ]; then
    if [ "$ajubatus_photographer" == "" ]; then
        exit_missing_args
    else
        photographer=$ajubatus_photographer
    fi
fi

if [ "$old_scheme" == "" ]; then
    if [ "$ajubatus_old_scheme" == "" ]; then
        exit_missing_args
    else
        old_scheme=$ajubatus_old_scheme
    fi
fi

# Rename photos in the working directory, or if multiple capture dates is
# enabled, go into directories one by one and rename the photos.
if [ ! "$multi_capture_date" == "$logic_true" ]; then
    # Now set the new naming scheme.
    new_scheme="${capture_date}_${photographer}_${camera}_"

    # Rename all files in the directory according to the naming scheme and make
    # sure everything is lowercase in the end.
    rename "s/$old_scheme/$new_scheme/" *
    rename -f 'y/A-Z/a-z/' *
else
    # Get a list of the directories that are present and use their names as the
    # capture dates.  Then enter each directory, rename the files, and then go
    # to the next one.

    dirs_list=$(ls -F1 |grep \/ |sed 's/\/$//' |tr '\n' ' ')
    dirs_to_traverse=($dirs_list)

    for capture_date in "${dirs_to_traverse[@]}"; do
        cd $capture_date
        new_scheme="${capture_date}_${photographer}_${camera}_"
        rename "s/$old_scheme/$new_scheme/" *
        rename -f 'y/A-Z/a-z/' *
        cd - >/dev/null
    done
fi
